pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('Github')
    }

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup") {
            steps {
                cleanWs()
            }
        }

        stage('Git: Code Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/kkiran98/Wanderlust-Mega-Project.git'
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            sed -i -e 's|wanderlust-backend:.*|wanderlust-backend:${params.BACKEND_DOCKER_TAG}|g' backend.yaml
                            sed -i -e 's|wanderlust-frontend:.*|wanderlust-frontend:${params.FRONTEND_DOCKER_TAG}|g' frontend.yaml
                        """
                    }
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'Github', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    sh '''
                    git config user.name "${GIT_USERNAME}"
                    git config user.email "kiranhk1102023@gmail.com"
                    git add .
                    git commit -m "Updated environment variables"
                    git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/kkiran98/Wanderlust-Mega-Project.git main
                    '''
                }
            }
        }
    }

    post {
        success {
            emailext(
                attachLog: true,
                from: 'kiranhk1102023@gmail.com',
                subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <p>Project: ${env.JOB_NAME}</p>
                        <p>Build Number: ${env.BUILD_NUMBER}</p>
                        <p>URL: ${env.BUILD_URL}</p>
                    </body>
                    </html>
                """,
                to: '3kiran0@gmail.com',
                mimeType: 'text/html'
            )
        }
        failure {
            emailext(
                attachLog: true,
                from: 'kiranhk1102023@gmail.com',
                subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <p>Project: ${env.JOB_NAME}</p>
                        <p>Build Number: ${env.BUILD_NUMBER}</p>
                    </body>
                    </html>
                """,
                to: '3kiran0@gmail.com',
                mimeType: 'text/html'
            )
        }
    }
}
